### ISSUE TITLE
Whoa! Very Cool..

### ISSUE THREAD

**Issue by bcookatpcsd** [KostyaEsmukov/smtp_to_telegram#11]
Just found this on docker hub.. can't wait to try it out.. 

I just wanted to ask.. is there a local queue? If I use the smtpd as part of an nms.. and the link from me to TG is down.. does the smtp_to_telegram accept responsibility for it and then when the link is up, pass the data to the bot?

Thanks in advance regardless.. this is just way cool to even think about..

**Comment by alecpetrosky** [comment]
From my own experience, if smtp_to_telegram has problems with TG, it just discards the message.

**Comment by KostyaEsmukov** [comment]
There is no queue, and there are no silent message discards either.

When a request to Telegram API is unsuccessful, the smtp message is rejected with a 5xx error: 

https://github.com/KostyaEsmukov/smtp_to_telegram/blob/8092fc365b902d160d3e3de6ceb7ca67a17392d0/smtp_to_telegram.go#L158

https://github.com/KostyaEsmukov/smtp_to_telegram/blob/8092fc365b902d160d3e3de6ceb7ca67a17392d0/smtp_to_telegram_test.go#L105-L113

A decent smtp client should enqueue the message on its side and retry later. If your sender doesn't do that, you can put a queueing MTA in front of smtp_to_telegram, such as exim4.

**Comment by akomakom** [comment]
FYI @KostyaEsmukov I am using postfix via smtp-to-telegram and I never get emails sent during outages (when telegram servers cannot be reached).  They are simply dropped.   

I'm also reading that [5xx errors are fatal and are not to be retried](https://en.wikipedia.org/wiki/List_of_SMTP_server_return_codes#%E2%80%94_5yz_Permanent_negative_completion), so I believe that postix is doing the right thing.  Perhaps the returned error code should be `421`?

That said, the postfix logs suggest that it may be retrying:

```
Nov  2 19:30:01 srv postfix/smtpd[750890]: connect from localhost[127.0.0.1]
Nov  2 19:30:01 srv postfix/smtpd[750890]: disconnect from localhost[127.0.0.1] helo=1 quit=1 commands=2
Nov  2 19:45:01 srv postfix/smtpd[751581]: connect from localhost[127.0.0.1]
Nov  2 19:45:01 srv postfix/smtpd[751581]: disconnect from localhost[127.0.0.1] helo=1 quit=1 commands=2
Nov  2 20:00:01 srv postfix/smtpd[752179]: connect from localhost[127.0.0.1]
Nov  2 20:00:01 srv postfix/smtpd[752179]: disconnect from localhost[127.0.0.1] helo=1 quit=1 commands=2
Nov  2 20:15:01 srv postfix/smtpd[752774]: connect from localhost[127.0.0.1]
```

and smtp-to-telegram at that time:
```
time="2024-11-02T18:36:03Z" level=info msg="Handle client [172.17.0.1], id: 58"
time="2024-11-02T18:36:03Z" level=debug msg="Writing response to client: \n220 7e9b8553234b SMTP Guerrilla(unknown) #58 (1) 2024-11-02T18:36:03Z\r\n"
time="2024-11-02T18:36:03Z" level=debug msg="Client sent: EHLO srv.XXXXXX.XXX"
time="2024-11-02T18:36:03Z" level=debug msg="Writing response to client: \n250-7e9b8553234b Hello\r\n250-SIZE 50000000\r\n250-PIPELINING\r\n250-ENHANCEDSTATUSCODES\r\n250 HELP\r\n"
time="2024-11-02T18:36:03Z" level=debug msg="Client sent: MAIL FROM:<XXXXX@XXXXXX.XXX>"
time="2024-11-02T18:36:03Z" level=debug msg="Writing response to client: \n250 2.1.0 OK\r\n"
time="2024-11-02T18:36:03Z" level=debug msg="Client sent: RCPT TO:<XXXXX@XXXXXX.XXX>"
time="2024-11-02T18:36:03Z" level=debug msg="Writing response to client: \n250 2.1.5 OK\r\n"
time="2024-11-02T18:36:03Z" level=debug msg="Client sent: DATA"
time="2024-11-02T18:36:03Z" level=debug msg="Writing response to client: \n354 Enter message, ending with '.' on a line by itself\r\n"
time="2024-11-02T18:36:04Z" level=error msg="Post \"https://api.telegram.org/bot***/sendMessage?disable_web_page_preview=true\": dial tcp: lookup api.telegram.org on X.Y.Z:53: server misbehaving"
time="2024-11-02T18:36:04Z" level=debug msg="Writing response to client: \n554 Error: Post \"https://api.telegram.org/bot***/sendMessage?disable_web_page_preview=true\": dial tcp: lookup api.telegram.org on 192.1
68.123.252:53: server misbehaving\r\n"
time="2024-11-02T18:36:04Z" level=debug msg="Client sent: QUIT"
time="2024-11-02T18:36:04Z" level=debug msg="Writing response to client: \n221 2.0.0 Bye\r\n"
```

After the outage postqueue is empty and the message is never sent.

**Comment by KostyaEsmukov** [comment]
@akomakom Good catch, thank you! I changed the error code to 421 in 204d318b749ec9cd3334ae2c907a2556a8a662cf, which indeed seems more appropriate here.
