### ISSUE TITLE
How to format in bold, italic, underline the message?

### ISSUE THREAD

**Issue by Hebusing** [KostyaEsmukov/smtp_to_telegram#15]
First of all, a massive thank you for this amazing program!!!

I was trying to format the subject in bold, and looking at the Telegram documentation (https://core.telegram.org/bots/api) I understand that there are different ways of sending: Markdown style, MarkdownV2 style and HTML style.

So I tried all options for ST_TELEGRAM_MESSAGE_TEMPLATE:

**Markdown style:**
`*{subject}*\n{body}`

**MarkdownV2 style:**
`*bold \*{subject}*\n{body}`

**HTML style:**
`<b>{subject}</b>\n{body}`

But none of them is working. Would you have any clue on this? Do you have an Environment variable for the style?

Thank you again!

**Comment by KostyaEsmukov** [comment]
This is not supported, see #22
