### ISSUE TITLE
How can i send messages via telnet?

### ISSUE THREAD

**Issue by sotoje** [KostyaEsmukov/smtp_to_telegram#20]
Hi, when i try to send a test message via telnet i am receiving "5.5.4 invalid address" message

**Comment by KostyaEsmukov** [comment]
Your message is invalid then.

Example: https://stackoverflow.com/a/9427114

A simplest message which will be accepted: https://github.com/KostyaEsmukov/smtp_to_telegram/blob/704fdb3daf8ea7f6db0e086d69bdc735b34dafbb/smtp_to_telegram_test.go#L68
