### ISSUE TITLE
Make max_size configurable for Guerrilla

### ISSUE THREAD

**Issue by janost** [KostyaEsmukov/smtp_to_telegram#21]
Thank you for this, very handy tool!

While sending emails with several attached images I encountered the following issue:
```
Error: maximum DATA size exceeded
```

The cause of this issue seems to be that Guerrilla defaults to 10M as the maximum message size. Guerrilla allow this to be configured, however currently `smtp_to_telegram` doesn't seem to override this configuration.

It would be useful for users to be able to override this limit, because although Telegram has a server side limit of 10MiB for each photo, `smtp_to_telegram` can receive several photos in a single email and send them one by one to a Telegram chat.

I would like to request to make this configuration exposed as an environment variable or command line option.

**Comment by KostyaEsmukov** [comment]
Good catch, thank you! Added `ST_SMTP_MAX_ENVELOPE_SIZE` env var / `--smtp-max-envelope-size` command line option to specify the Guerrilla's MaxSize property, and raised the default from 10m to 50m.

**Comment by janost** [comment]
Thank you for implementing this!
