### ISSUE TITLE
Images as picture and not as file

### ISSUE THREAD

**Issue by n3roGit** [KostyaEsmukov/smtp_to_telegram#23]
First of all: A very great tool, what you have built here! It's great that you can now finally send larger files and attachments work!

However, one thing could be changed. Currently, images are sent as a file and must first be downloaded. It would be great if you could attach them as images. Then you can look at them directly and also zoom in.

![image](https://user-images.githubusercontent.com/8565847/132816855-b7437138-e74a-4c13-af73-70b06e29fd5e.png)

**Comment by KostyaEsmukov** [comment]
> Currently, images are sent as a file and must first be downloaded.

That wasn't the case for .jpg images.

I have made .png to be sent that way too: looks like Telegram API supports that.
