### ISSUE TITLE
Synology Disk Station - Envelope Error

### ISSUE THREAD

**Issue by brianjw** [KostyaEsmukov/smtp_to_telegram#30]
Hello,

I am following a guide for implementing Telegram notifications on my Synology Disk Station: https://medium.com/@nicholaschum/synology-dsm-6-x-telegram-bot-alerts-2f069eb3e9f2

I receive an error from Synology when attempting to send a test "Email":
`Test mail failed to send. Please check your settings and try again.
554 5.5.0 Error: transaction timeout`

In the Docker log, these are the errors I am seeing:
`15:20:29   354 Enter message, ending with '.' on a line by itself`
`15:20:30   ERRO[0021] Envelope error: [W] Plain Text from HTML: Message did not contain a text/plain part`
`15:21:00   ERRO[0051] Backend has timed out while saving email`
`15:21:00   DEBU[0051] Writing response to client:`
`15:21:00   554 5.5.0 Error: transaction timeout`
`15:21:00   DEBU[0051] Client sent:`
`15:21:00   WARN[0051] Client closed the connection: 172.17.0.1      error=EOF`

Any ideas what I am doing wrong? New to this project, but not new to Docker/Synology. Thanks!

**Comment by KostyaEsmukov** [comment]
Looks like your application is sending malformed emails.
