### ISSUE TITLE
userid instead chatid

### ISSUE THREAD

**Issue by stefanocudini** [KostyaEsmukov/smtp_to_telegram#39]
there is possibility to indicate the user id instead of the chat id??? this is a bit complicated to obtain

**Comment by KostyaEsmukov** [comment]
Is this a question or a statement?

**Comment by stefanocudini** [comment]
a question, sorry

**Comment by KostyaEsmukov** [comment]
Then the answer is no: if I knew an easier way I would've documented it.

If you find one -- feel free to contribute a doc update.
