### ISSUE TITLE
Unable to receive images in telegram

### ISSUE THREAD

**Issue by duanedtp** [KostyaEsmukov/smtp_to_telegram#4]
System works but i'm unable to receive or pull images from the email. I'm using this to relay motion events from my security cameras, which takes a snapshot and attaches it to the email. Is it a formatting issue?

**Comment by KostyaEsmukov** [comment]
HTML and attachments are not supported, only plaintext is being forwarded, see https://github.com/KostyaEsmukov/smtp_to_telegram/blob/8092fc365b902d160d3e3de6ceb7ca67a17392d0/smtp_to_telegram_test.go#L157-L186

Converting HTML to Telegram markup would be very complex, so I don't think adding that support would be feasible.

However, simply bypassing image attachments as telegram file uploads should be easy to implement, for that a PR would be welcome.
