### ISSUE TITLE
Arm v6 Docker Image

### ISSUE THREAD

**Issue by MarcelloPercoco** [KostyaEsmukov/smtp_to_telegram#45]
Hi.

It's possible for you to build even the armv6 version of the docker image?

It will be useful for people that have docker services on, as example, raspberry, Oracle CLoud Amper instances and so on.

Thnaks.

**Comment by KostyaEsmukov** [comment]
Please take a moment to make a search request before opening an issue: https://github.com/KostyaEsmukov/smtp_to_telegram/issues?q=arm

The answer to this question already exists: https://github.com/KostyaEsmukov/smtp_to_telegram/issues/3#issuecomment-619514690
