### ISSUE TITLE
Docker armhf builds (raspberry pi)

### ISSUE THREAD

**Issue by alecpetrosky** [KostyaEsmukov/smtp_to_telegram#5]
Are armhf builds possible? Is there any obstacle as to my knowledge, go should support this architecture?

**Comment by alecpetrosky** [comment]
Oh, as I see in https://github.com/KostyaEsmukov/smtp_to_telegram/issues/3, such builds are feasible but no plans to support them. Have I understood it correctly?

**Comment by KostyaEsmukov** [comment]
Yes, I have no plans on supporting arm* builds. It should work, but I'm not sure as I didn't check.

**Comment by KostyaEsmukov** [comment]
> Is there any obstacle as to my knowledge, go should support this architecture?

The code of this library should be portable, but an obstacle might be in some of the dependencies, which might not work on arm*.

**Comment by alecpetrosky** [comment]
Yesterday, with the minor modifications of source, I successfully compiled it for arm7 and so far it works great on Raspberry Pi 4. As I use Raspi on a permanent basis, I'll take care of arm7 builds.
