### ISSUE TITLE
554 Error

### ISSUE THREAD

**Issue by ander1k** [KostyaEsmukov/smtp_to_telegram#50]
Доброго дня..

есть возможность подсказать куда копать на Synology?

Не удалось отправить тестовое письмо. Проверьте настройки и повторите попытку.
554 Error: Post "https://api.telegram.org/bot***/sendMessage?disable_web_page_preview=true": dial tcp: lookup api.telegram.org on 192.168.1.1:53: read udp 172.17.0.5:42391->192.168.1.1:53: i/o timeout

ПС: Уведомления через Push в телегу приходят, через смс тоже пробовал приходят, хочу настроить через мыло

**Comment by KostyaEsmukov** [comment]
You'll have to solve your issue yourself, I don't have enough capacity for helping.
