### ISSUE TITLE
Long text messages, sending fails

### ISSUE THREAD

**Issue by alecpetrosky** [KostyaEsmukov/smtp_to_telegram#6]
Is the an option to trim automatically messages which exceed maximum length allowed by Telegram instead of fail? I guess the most common use case scenario for smtp_to_telegram is sending automated notifications from the server. Often, we aren't in control of message length. And IMHO it's better to trim message than discard it.

**Comment by KostyaEsmukov** [comment]
There's no such option at this moment. I never faced such a problem, but I think this is a good idea, so a PR would be welcome.

But I think instead of trimming the message it would be better to split it to multiple smaller ones.
