### ISSUE TITLE
Add HEALTHCHECK for the container

### ISSUE THREAD

**Issue by alecpetrosky** [KostyaEsmukov/smtp_to_telegram#7]
This mechanism is very useful for container health status monitoring and it allows restart containers with faulty state.

**Comment by alecpetrosky** [comment]
Create PR https://github.com/KostyaEsmukov/smtp_to_telegram/pull/8

**Comment by KostyaEsmukov** [comment]
Replied here why I don't want this: https://github.com/KostyaEsmukov/smtp_to_telegram/pull/8#issuecomment-907867273
